baseURL = 'https://retromultiplayer.com/'
languageCode = 'en-us'
title = 'RetroMultiplayer'
theme = 'lynx'
disableKinds = ["taxonomy", "term"] # unsupported by Lynx theme

[author]
    name = "RetroMultiplayer" # copyright label on page footer
