baseURL = 'https://retromultiplayer.com/'
languageCode = 'en-us'
title = 'RetroMultiplayer'
theme = 'lynx'
disableKinds = ["taxonomy", "term"] # unsupported by Lynx theme

[author]
    name = "RetroMultiplayer" # copyright label on page footer

[params.author]
    headline = "Gaming community in Riga, Latvia"
    image = "rmp_logo.png"
    links = [
        { discord = "https://discord.gg/wuvKNmurPR" },
        { facebook = "https://www.facebook.com/RetroMultiplayer" },
        { instagram = "https://www.instagram.com/retromultiplayer/" },
        { tiktok = "https://www.tiktok.com/@retromultiplayer.com" },
        { youtube = "https://www.youtube.com/@retromultiplayer4666" }
    ]
